const express = require("express");
const { z } = require("zod");
const { sql, getPool, query } = require("../../db/pool");
const { asyncHandler } = require("../../middleware/asyncHandler");
const { requireAuth } = require("../../middleware/auth");
const { getHolidayDates } = require("../../db/holidayPool");
const { isYmd, parseHm, parseWeekdays, mailSectionFor, UNITS, MAX_REPEAT_EVERY } =
  require("../../services/personalTodoReminderService");

// Personal Kanban to-do board. One private board per user — deliberately NOT
// section scoped (it follows the person across every section/branch), so this
// router only requires auth and never resolves a section. Columns and cards are
// loaded together and saved replace-all, mirroring the weekly-plan PUT: for a
// single-user board there is no concurrent-editor problem to guard against.
const router = express.Router();
router.use(requireAuth);

// Seeded when a user opens their board for the very first time.
const DEFAULT_COLUMNS = [
  { title: "Wait", color: "#e0982a" },
  { title: "In Process", color: "#2f6bed" },
  { title: "Done", color: "#23a35a" }
];

// Column widths (patch_personal_todo_layout.sql) are optional: if the patch
// has not been applied yet the board still works, it just stops remembering the
// sizes. Checked once per process, then cached.
const MIN_COL_WIDTH = 200;
const MAX_COL_WIDTH = 640;
const DEFAULT_COL_WIDTH = 280;
let layoutColumnsReady = null;

// Card reminders (patch_personal_todo_reminders.sql) are optional the same way:
// without the patch the board still loads and saves, it simply offers no
// reminders. Same one-query-then-cache check.
let reminderTablesReady = null;

const MAX_REMINDERS_PER_CARD = 20;

// How long a deleted card's reminders are kept, orphaned, before they are
// really removed. It only has to outlive the board's Undo — a week is generous
// and costs a handful of rows.
const ORPHAN_KEEP_DAYS = 7;

async function hasLayoutColumns() {
  if (layoutColumnsReady !== null) return layoutColumnsReady;
  try {
    const row = (await query(
      `SELECT COUNT(*) AS n FROM sys.columns
       WHERE (object_id = OBJECT_ID('personal_todo_columns') AND name = 'width')
          OR (object_id = OBJECT_ID('users') AND name = 'personal_todo_col_width')`
    )).recordset[0];
    layoutColumnsReady = Number(row?.n ?? 0) >= 2;
  } catch {
    layoutColumnsReady = false;
  }
  return layoutColumnsReady;
}

async function hasReminderTables() {
  if (reminderTablesReady !== null) return reminderTablesReady;
  try {
    const row = (await query(
      `SELECT
         (SELECT COUNT(*) FROM sys.columns
           WHERE object_id = OBJECT_ID('personal_todo_reminders') AND name = 'orphaned_at') AS t,
         (SELECT COUNT(*) FROM sys.columns
           WHERE object_id = OBJECT_ID('personal_todo_items')
             AND name IN ('uid', 'reminder_enabled')) AS c`
    )).recordset[0];
    reminderTablesReady = Number(row?.t ?? 0) >= 1 && Number(row?.c ?? 0) >= 2;
  } catch {
    reminderTablesReady = false;
  }
  return reminderTablesReady;
}

// Clamp an incoming width to something a board can actually show; null/invalid
// means "no explicit width — follow the board default".
function normaliseWidth(value) {
  const n = Number(value);
  if (!Number.isFinite(n) || n <= 0) return null;
  return Math.min(MAX_COL_WIDTH, Math.max(MIN_COL_WIDTH, Math.round(n)));
}

// A card's stable identity, generated by the client. Anything that isn't a
// plausible id is dropped rather than stored, so it can never be used to reach
// another user's rows (every query is scoped by user_id anyway).
function normaliseUid(value) {
  const uid = `${value ?? ""}`.trim();
  return /^[A-Za-z0-9_-]{6,40}$/.test(uid) ? uid : null;
}

// One reminder as the API talks about it.
function reminderJson(row) {
  return {
    id: row.id,
    itemUid: row.item_uid,
    enabled: row.enabled === true || row.enabled === 1,
    startDate: row.start_date,
    time: row.remind_time,
    recurring: row.is_recurring === true || row.is_recurring === 1,
    repeatEvery: row.repeat_every,
    repeatUnit: row.repeat_unit,
    weekdays: parseWeekdays(row.weekdays),
    untilDate: row.until_date ?? null,
    lastSentAt: row.last_sent_at ?? null
  };
}

async function loadReminders(userId) {
  if (!(await hasReminderTables())) return new Map();
  const rows = (await query(
    `SELECT id, item_uid, enabled, start_date, remind_time, is_recurring,
            repeat_every, repeat_unit, weekdays, until_date, last_sent_at
     FROM personal_todo_reminders
     WHERE user_id = @userId AND orphaned_at IS NULL
     ORDER BY start_date, remind_time, id`,
    { userId }
  )).recordset;
  const byUid = new Map();
  for (const row of rows) {
    if (!byUid.has(row.item_uid)) byUid.set(row.item_uid, []);
    byUid.get(row.item_uid).push(reminderJson(row));
  }
  return byUid;
}

async function loadBoard(userId) {
  const withLayout = await hasLayoutColumns();
  const withReminders = await hasReminderTables();
  const columns = (await query(
    `SELECT id, title, color, sort_order${withLayout ? ", width" : ""} FROM personal_todo_columns
     WHERE user_id = @userId ORDER BY sort_order, id`,
    { userId }
  )).recordset;
  const items = (await query(
    `SELECT id, column_id, content, sort_order${withReminders ? ", uid, reminder_enabled" : ""}
     FROM personal_todo_items
     WHERE user_id = @userId ORDER BY sort_order, id`,
    { userId }
  )).recordset;
  const remindersByUid = await loadReminders(userId);
  const itemsByColumn = new Map();
  for (const it of items) {
    if (!itemsByColumn.has(it.column_id)) itemsByColumn.set(it.column_id, []);
    itemsByColumn.get(it.column_id).push({
      id: it.id,
      content: it.content,
      uid: withReminders ? (it.uid ?? null) : null,
      // Defaults on: a card the user has never touched is simply "not silenced".
      reminderEnabled: withReminders ? it.reminder_enabled !== false && it.reminder_enabled !== 0 : true,
      reminders: (withReminders && it.uid ? remindersByUid.get(it.uid) : null) ?? []
    });
  }
  return columns.map(c => ({
    id: c.id,
    title: c.title,
    color: c.color ?? null,
    // null → this column follows the board's default width.
    width: withLayout ? (c.width ?? null) : null,
    items: itemsByColumn.get(c.id) ?? []
  }));
}

// The user's default column width (what new columns start at). Falls back to
// the shared default when unset or when the layout patch is missing.
async function loadDefaultWidth(userId) {
  if (!(await hasLayoutColumns())) return DEFAULT_COL_WIDTH;
  const row = (await query(
    "SELECT personal_todo_col_width FROM users WHERE id = @userId",
    { userId }
  )).recordset[0];
  return normaliseWidth(row?.personal_todo_col_width) ?? DEFAULT_COL_WIDTH;
}

async function boardResponse(userId) {
  const remindersAvailable = await hasReminderTables();
  return {
    columns: await loadBoard(userId),
    defaultWidth: await loadDefaultWidth(userId),
    // The frontend hides the whole reminder UI when the patch is not applied,
    // rather than offering a switch that silently does nothing.
    remindersAvailable,
    // Whether a reminder set here could actually be DELIVERED. Personal
    // reminders ride on the mail switch of a section this person belongs to
    // (see mailSectionFor), and nothing in the frontend can work that out for
    // itself — so the editor is told, and says so instead of going quiet.
    mailEnabled: remindersAvailable ? (await mailSectionFor(userId)) !== null : false
  };
}

// Read the board; seed the three default columns the FIRST time it's opened.
// Seeding is gated on users.personal_todo_initialized (not on emptiness) so a
// user who deletes every column keeps an empty board instead of having the
// defaults resurrected.
router.get("/", asyncHandler(async (req, res) => {
  const flag = (await query(
    "SELECT personal_todo_initialized FROM users WHERE id = @userId",
    { userId: req.user.id }
  )).recordset[0];
  const initialized = flag?.personal_todo_initialized === true || flag?.personal_todo_initialized === 1;

  if (!initialized) {
    let order = 0;
    for (const c of DEFAULT_COLUMNS) {
      await query(
        `INSERT INTO personal_todo_columns (user_id, title, color, sort_order)
         VALUES (@userId, @title, @color, @sortOrder)`,
        { userId: req.user.id, title: c.title, color: c.color, sortOrder: order++ }
      );
    }
    await query(
      "UPDATE users SET personal_todo_initialized = 1 WHERE id = @userId",
      { userId: req.user.id }
    );
  }
  res.json(await boardResponse(req.user.id));
}));

// Replace the whole board in one transaction. The client sends the columns (in
// order — that order IS the left-to-right layout) each with its cards (in
// order) and optional width; row ids are reassigned on save, which is exactly
// why a card's REMINDERS hang off its client-generated uid instead. Reminders
// are never rewritten here: the save only prunes the ones whose card has gone.
router.put("/", asyncHandler(async (req, res) => {
  const schema = z.object({
    defaultWidth: z.number().optional().nullable(),
    columns: z.array(z.object({
      title: z.string().optional().nullable(),
      color: z.string().max(20).optional().nullable(),
      width: z.number().optional().nullable(),
      items: z.array(z.object({
        content: z.string().optional().nullable(),
        uid: z.string().max(40).optional().nullable(),
        reminderEnabled: z.boolean().optional()
      })).optional().default([])
    })).max(50).optional().default([])
  });
  const input = schema.parse(req.body);
  const withLayout = await hasLayoutColumns();
  const withReminders = await hasReminderTables();

  // Every uid that survives this save. Reminders belonging to anything else are
  // deleted at the end — deleting a card takes its alarms with it.
  const survivingUids = [];

  const pool = await getPool();
  const tx = new sql.Transaction(pool);
  await tx.begin();
  try {
    const run = (text, params = {}) => {
      const request = new sql.Request(tx);
      for (const [key, value] of Object.entries(params)) {
        request.input(key, value === undefined ? null : value);
      }
      return request.query(text);
    };

    // Items reference columns, so clear items first.
    await run("DELETE FROM personal_todo_items WHERE user_id = @userId", { userId: req.user.id });
    await run("DELETE FROM personal_todo_columns WHERE user_id = @userId", { userId: req.user.id });
    // Any save marks the board initialized so GET won't re-seed defaults over
    // an intentionally empty board.
    await run("UPDATE users SET personal_todo_initialized = 1 WHERE id = @userId", { userId: req.user.id });
    if (withLayout && input.defaultWidth !== undefined) {
      await run(
        "UPDATE users SET personal_todo_col_width = @width WHERE id = @userId",
        { userId: req.user.id, width: normaliseWidth(input.defaultWidth) }
      );
    }

    let colOrder = 0;
    for (const col of input.columns) {
      const title = `${col.title ?? ""}`.slice(0, 120).trim() || "Untitled";
      const color = col.color ? `${col.color}`.slice(0, 20) : null;
      const width = normaliseWidth(col.width);
      const inserted = await run(
        withLayout
          ? `INSERT INTO personal_todo_columns (user_id, title, color, sort_order, width)
             OUTPUT INSERTED.id
             VALUES (@userId, @title, @color, @sortOrder, @width)`
          : `INSERT INTO personal_todo_columns (user_id, title, color, sort_order)
             OUTPUT INSERTED.id
             VALUES (@userId, @title, @color, @sortOrder)`,
        withLayout
          ? { userId: req.user.id, title, color, sortOrder: colOrder++, width }
          : { userId: req.user.id, title, color, sortOrder: colOrder++ }
      );
      const columnId = inserted.recordset[0].id;
      let itemOrder = 0;
      for (const item of (col.items ?? [])) {
        const content = `${item.content ?? ""}`.slice(0, 1000).trim();
        if (!content) continue; // drop blank cards
        const uid = normaliseUid(item.uid);
        if (uid) survivingUids.push(uid);
        const reminderEnabled = item.reminderEnabled === false ? 0 : 1;
        await run(
          withReminders
            ? `INSERT INTO personal_todo_items (user_id, column_id, content, sort_order, uid, reminder_enabled)
               VALUES (@userId, @columnId, @content, @sortOrder, @uid, @reminderEnabled)`
            : `INSERT INTO personal_todo_items (user_id, column_id, content, sort_order)
               VALUES (@userId, @columnId, @content, @sortOrder)`,
          withReminders
            ? { userId: req.user.id, columnId, content, sortOrder: itemOrder++, uid, reminderEnabled }
            : { userId: req.user.id, columnId, content, sortOrder: itemOrder++ }
        );
      }
    }

    if (withReminders) {
      // A card that has left the board takes its alarms out of service — but
      // NOT out of the table. Deleting a card is undoable on the board, so its
      // reminders have to be undoable too, and they have to come back carrying
      // `last_sent_key`: an alarm that already rang this morning must not ring
      // again just because the card was deleted and restored this afternoon.
      // So they are ORPHANED here, un-orphaned the moment the uid is back, and
      // only actually deleted once the undo is long past.
      //
      // Nothing orphaned can fire meanwhile: the reminder scan inner-joins
      // personal_todo_items on the uid, and there is no row to join to.
      //
      // Inlining the uids is safe — normaliseUid() has already restricted them
      // to [A-Za-z0-9_-].
      const list = survivingUids.map(u => `'${u}'`).join(",");
      await run(
        list
          ? `UPDATE personal_todo_reminders SET orphaned_at = SYSUTCDATETIME()
             WHERE user_id = @userId AND orphaned_at IS NULL AND item_uid NOT IN (${list})`
          : `UPDATE personal_todo_reminders SET orphaned_at = SYSUTCDATETIME()
             WHERE user_id = @userId AND orphaned_at IS NULL`,
        { userId: req.user.id }
      );
      if (list) {
        await run(
          `UPDATE personal_todo_reminders SET orphaned_at = NULL
           WHERE user_id = @userId AND orphaned_at IS NOT NULL AND item_uid IN (${list})`,
          { userId: req.user.id }
        );
      }
      await run(
        `DELETE FROM personal_todo_reminders
         WHERE user_id = @userId AND orphaned_at IS NOT NULL
           AND orphaned_at < DATEADD(day, -${ORPHAN_KEEP_DAYS}, SYSUTCDATETIME())`,
        { userId: req.user.id }
      );
    }

    await tx.commit();
  } catch (err) {
    await tx.rollback();
    throw err;
  }

  res.json(await boardResponse(req.user.id));
}));

// Company holidays in a date range, so the calendar view can grey those days
// beside the weekends. The weekly plan has the same endpoint, but that router
// resolves a section and this board deliberately does not — it opens from the
// section picker too, where there is no section to resolve.
//
// getHolidayDates never throws: an unconfigured or unreachable holiday DB comes
// back as `configured:false` with no dates, and the calendar simply greys the
// weekends only.
router.get("/holidays", asyncHandler(async (req, res) => {
  const ymd = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "expected YYYY-MM-DD");
  const from = ymd.parse(req.query.from);
  const to = ymd.parse(req.query.to);
  res.json(await getHolidayDates(from, to));
}));

// ---------------------------------------------------------------------------
// Card reminders
// ---------------------------------------------------------------------------

// One reminder as the client sends it. A non-repeating reminder is just a date
// and a time; the repeat fields are ignored unless `recurring` is on.
const reminderSchema = z.object({
  id: z.number().int().optional().nullable(),
  enabled: z.boolean().optional(),
  startDate: z.string().max(10),
  time: z.string().max(5),
  recurring: z.boolean().optional(),
  repeatEvery: z.number().int().optional().nullable(),
  repeatUnit: z.string().max(10).optional().nullable(),
  weekdays: z.array(z.number().int()).max(7).optional().nullable(),
  untilDate: z.string().max(10).optional().nullable()
});

// Normalise one reminder to exactly what goes in the row, or null if it does not
// describe a real moment. Everything the schedule is judged on is written here,
// so this is also what the "did the schedule change?" comparison reads.
function normaliseReminder(input) {
  const startDate = `${input.startDate ?? ""}`.trim();
  const time = `${input.time ?? ""}`.trim();
  if (!isYmd(startDate) || parseHm(time) === null) return null;
  const recurring = input.recurring === true;
  const unit = `${input.repeatUnit ?? "week"}`.toLowerCase();
  const until = `${input.untilDate ?? ""}`.trim();
  return {
    enabled: input.enabled === false ? 0 : 1,
    startDate,
    // Stored as the canonical 'HH:mm' so '9:00' and '09:00' are one occurrence
    // key, not two.
    time: time.length === 4 ? `0${time}` : time,
    recurring: recurring ? 1 : 0,
    repeatEvery: recurring
      ? Math.max(1, Math.min(MAX_REPEAT_EVERY, Number(input.repeatEvery) || 1))
      : 1,
    repeatUnit: recurring && UNITS.has(unit) ? unit : "week",
    weekdays: recurring && unit === "week" && Array.isArray(input.weekdays)
      ? (parseWeekdays(input.weekdays.join(",")).join(",") || null)
      : null,
    // "Until" only means anything for a repeat, and an end before the start is
    // no end at all.
    untilDate: recurring && isYmd(until) && until >= startDate ? until : null
  };
}

// The fields a delivery is keyed on. Two reminders that agree here are the same
// schedule, so the one-shot ledger survives an unrelated edit (renaming, or
// simply pressing Save) instead of re-arming an occurrence already delivered.
function scheduleSignature(r) {
  return [r.startDate, r.time, r.recurring, r.repeatEvery, r.repeatUnit, r.weekdays ?? "", r.untilDate ?? ""].join("|");
}

function signatureOfRow(row) {
  return scheduleSignature({
    startDate: row.start_date,
    time: row.remind_time,
    recurring: row.is_recurring === true || row.is_recurring === 1 ? 1 : 0,
    repeatEvery: row.repeat_every,
    repeatUnit: row.repeat_unit,
    weekdays: row.weekdays,
    untilDate: row.until_date
  });
}

// Replace the reminder list of ONE card. Rows the client still knows the id of
// are updated in place (keeping their ledger when the schedule is unchanged),
// new ones are inserted and the rest are deleted.
router.put("/items/:uid/reminders", asyncHandler(async (req, res) => {
  if (!(await hasReminderTables())) {
    return res.status(503).json({ error: "REMINDERS_NOT_AVAILABLE" });
  }
  const uid = normaliseUid(req.params.uid);
  if (!uid) return res.status(400).json({ error: "INVALID_ITEM_UID" });

  const input = z.object({
    reminders: z.array(reminderSchema).max(MAX_REMINDERS_PER_CARD).optional().default([])
  }).parse(req.body);

  const existing = (await query(
    `SELECT id, start_date, remind_time, is_recurring, repeat_every, repeat_unit,
            weekdays, until_date
     FROM personal_todo_reminders WHERE user_id = @userId AND item_uid = @uid`,
    { userId: req.user.id, uid }
  )).recordset;
  const existingById = new Map(existing.map(row => [row.id, row]));

  const keptIds = [];
  for (const raw of input.reminders) {
    const r = normaliseReminder(raw);
    if (!r) continue; // not a real moment — silently dropped
    const current = raw.id ? existingById.get(Number(raw.id)) : null;
    const params = {
      userId: req.user.id,
      uid,
      enabled: r.enabled,
      startDate: r.startDate,
      time: r.time,
      recurring: r.recurring,
      repeatEvery: r.repeatEvery,
      repeatUnit: r.repeatUnit,
      weekdays: r.weekdays,
      untilDate: r.untilDate
    };
    if (current) {
      // A changed schedule re-arms the reminder; an unchanged one keeps its
      // ledger so today's delivered occurrence is not sent a second time.
      const same = signatureOfRow(current) === scheduleSignature(r);
      await query(
        `UPDATE personal_todo_reminders
         SET enabled = @enabled, start_date = @startDate, remind_time = @time,
             is_recurring = @recurring, repeat_every = @repeatEvery,
             repeat_unit = @repeatUnit, weekdays = @weekdays, until_date = @untilDate,
             -- Editing a card's reminders is proof the card is back.
             orphaned_at = NULL,
             ${same ? "" : "last_sent_key = NULL,"} updated_at = SYSUTCDATETIME()
         WHERE id = @id AND user_id = @userId`,
        { ...params, id: current.id }
      );
      keptIds.push(current.id);
    } else {
      const inserted = (await query(
        `INSERT INTO personal_todo_reminders
           (user_id, item_uid, enabled, start_date, remind_time, is_recurring,
            repeat_every, repeat_unit, weekdays, until_date)
         OUTPUT INSERTED.id
         VALUES (@userId, @uid, @enabled, @startDate, @time, @recurring,
                 @repeatEvery, @repeatUnit, @weekdays, @untilDate)`,
        params
      )).recordset[0];
      keptIds.push(inserted.id);
    }
  }

  const gone = existing.map(row => row.id).filter(id => !keptIds.includes(id));
  for (const id of gone) {
    await query(
      "DELETE FROM personal_todo_reminders WHERE id = @id AND user_id = @userId",
      { id, userId: req.user.id }
    );
  }

  const rows = (await query(
    `SELECT id, item_uid, enabled, start_date, remind_time, is_recurring,
            repeat_every, repeat_unit, weekdays, until_date, last_sent_at
     FROM personal_todo_reminders
     WHERE user_id = @userId AND item_uid = @uid
     ORDER BY start_date, remind_time, id`,
    { userId: req.user.id, uid }
  )).recordset;
  res.json({ reminders: rows.map(reminderJson) });
}));

module.exports = router;
